const STRING = {
  ADDITIONAL_DESCRIPTION: "추가설명",
  ALL: "모두",
  BASE_VALUE_ERROR: "이벤트 가격을 입력해주세요",
  BUY_BASE_TEXT: "개 구매하면",
  BUY_NUMBER: "구매 수량",
  CANCEL: "취소",
  CODE: "CODE",
  CONFIRM: "확인",
  CONNECTED_BLOG_LABEL: "블로그 연결",
  CONNECTED_SPOT: "스팟 연결",
  CREATE: "생성",
  CREATED_AT: "생성일자",
  CREATE_NEW_EVENT: "이벤트 생성",
  CREATE_NEW_TIP: "팁 생성하기",
  CREATE_SUCCESS: "생성 성공",
  DELETE: "삭제",
  DELETE_CONFIRM: "정말 삭제하시겠어요?",
  DELETE_SUCCESS: "삭제 성공",
  DISCOUNT_PRICE: "할인가",
  EDIT: "수정",
  EMPTY: "",
  EVENT_PRICE: "이벤트 가격",
  EVENT_TYPE: "이벤트 유형",
  EVENT_PERIOD: "이벤트 기간",
  GIFT_NUMBER: "증정 수량",
  GIFT_TEXT: "개 증정",
  ID_PLACEHOLDER: "Email",
  IMAGE_UPLOAD_SUCCESS: "이미지 업로드 성공",
  IS_ACTIVE: "공개여부",
  IS_NOT_RESERVABLE: "예약불가",
  IS_ONGOING: "진행여부",
  IS_RESERVABLE: "예약가능",
  LOGIN: "Login",
  LOGOUT: "Logout",
  MAIN_IMAGE_LABEL: "메인 이미지",
  MANAGER: "담당자",
  NAME: "이름",
  NUMBER_PLACEHOLDER: "숫자만 입력 가능합니다",
  OPEN_NEW_EVENT_MODAL: "새 이벤트 생성",
  OPEN_NEW_TIP_MODAL: "새 팁 생성",
  OPTION_BASE_PRICE: "옵션정가",
  PASSWORD_PLACEHOLDER: "Password",
  PERIOD: "기간",
  PRODUCT_DESCRIPTION: "Everyone is an insider",
  PRODUCT_NAME: "상품명",
  PRODUCT_TITLE: "Creatrip Admin",
  REPRESENTATIVE_PRODUCT_ORIGIN_PRICE: "대표상품 정가",
  REPRESENTATIVE_PRODUCT_DC_PRICE: "대표상품 할인가",
  SAVE: "저장하기",
  SELECT_LANGUAGE_LABEL: "언어 선택",
  SET_PERIOD: "기간 설정",
  SPOT_EVENT: "스팟 이벤트",
  SPOT_EVENT_SEARCHBAR_PLACEHOLDER: "상품명, 스팟명 검색",
  STATUS: "상태",
  TIP_TITLE: "팁 제목",
  TITLE: "제목",
  TITLE_LABEL: "제목",
  TITLE_UPDATE_SUCCESS: "제목 저장 성공",
  TOGGLE_ACTIVE_SUCCESS: "공개 상태 변경 성공",
  TYPE: "유형",
  UPDATE_SUCCESS: "업데이트 성공",
};

export default STRING;
