const STRING = {
  EMPTY: "",
  ALL: "모두",
  PRODUCT_TITLE: "Creatrip Admin",
  PRODUCT_DESCRIPTION: "Everyone is an insider",
  LOGIN: "Login",
  LOGOUT: "Logout",
  TIP_TITLE: "팁 제목",
  TITLE: "제목",
  NAME: "이름",
  TYPE: "유형",
  PERIOD: "기간",
  STATUS: "상태",
  IS_ONGOING: "진행여부",
  CODE: "CODE",
  MANAGER: "담당자",
  CREATED_AT: "생성일자",
  IS_ACTIVE: "공개여부",
  TOGGLE_ACTIVE_SUCCESS: "공개 상태 변경 성공",
  DELETE: "삭제",
  SAVE: "저장하기",
  TITLE_UPDATE_SUCCESS: "제목 저장 성공",
  CREATE_SUCCESS: "생성 성공",
  UPDATE_SUCCESS: "업데이트 성공",
  IMAGE_UPLOAD_SUCCESS: "이미지 업로드 성공",
  DELETE_CONFIRM: "정말 삭제하시겠어요?",
  DELETE_SUCCESS: "삭제 성공",
  OPEN_NEW_TIP_MODAL: "새 팁 생성",
  CREATE_NEW_TIP: "팁 생성하기",
  CONFIRM: "확인",
  CREATE: "생성",
  CANCEL: "취소",
  EVNET_TYPE: "이벤트 유형",
  EVNET_PERIOD: "이벤트 기간",
  SELECT_LANGUAGE_LABEL: "언어 선택*",
  TITLE_LABEL: "제목*",
  CONNECTED_BLOG_LABEL: "블로그 연결*",
  MAIN_IMAGE_LABEL: "메인 이미지*",
  ID_PLACEHOLDER: "Email",
  PASSWORD_PLACEHOLDER: "Password",
};

export default STRING;
